run:
  timeout: 5m
  tests: true
linters:
  enable-all: true
  disable:
    - gomnd # Replaced by mnd
    - exhaustruct
    - tagliatelle
    - interfacebloat
    - depguard
    - ireturn
  fast: false
linters-settings:
  gocritic:
    enabled-tags:
      - style
      - experimental
      - performance
      - diagnostic
      - opinionated

  govet:
    enable-all: true
    disable:
      - shadow
      - fieldalignment

  gci:
    sections:
      - standard
      - default
      - localmodule

  funlen:
    lines: 120
  
  lll:
    line-length: 140

  gomodguard:
    blocked:
      modules:
        - github.com/urfave/cli:
            recommendations:
              - github.com/urfave/cli/v2

  varnamelen:
    # The longest distance, in source lines, that is being considered a "small scope." (defaults to 5)
    # Variables used in at most this many lines will be ignored.
    max-distance: 12
    # Ignore "ok" variables that hold the bool return value of a type assertion. (defaults to false)
    ignore-type-assert-ok: true
    # Ignore "ok" variables that hold the bool return value of a map index. (defaults to false)
    ignore-map-index-ok: true
    # Ignore "ok" variables that hold the bool return value of a channel receive. (defaults to false)
    ignore-chan-recv-ok: true
    # Optional list of variable names that should be ignored completely. (defaults to empty list)
    ignore-names:
      - wg
      - n
